// 通用图标目录。策略、节点组的图标选择器里「其他」那一栏就是这张表:
// 交通、运动、花草、建筑、家居、人物性别、办公杂物——国旗和公司标识之外,总有些组
// 只是想要一个一眼认得出的记号。
//
// 图形是 Twemoji v15 的彩色 emoji,文件在 src/assets/misc/(CC-BY 4.0,见那边的
// README)。这里只存有哪些、叫什么、怎么搜,图形本身由浏览器按需去取。
// zh/en 与 keywords 一起参与搜索:输「汽车」「car」「车」都该找到同一个。
export interface MiscIcon {
  id: string
  zh: string
  en: string
  keywords: string[]
}

export const MISC_ICONS: MiscIcon[] = [
  // 直连的几种画法:靶心、箭头、绿灯、对勾、公路
  { id: 'dart', zh: '靶心', en: 'Bullseye', keywords: ['direct', '直连', '靶心', '飞镖', '目标', 'target'] },
  { id: 'dart-tile', zh: '靶心(白底)', en: 'Bullseye (tile)', keywords: ['direct', '直连', '靶心', '飞镖', '目标', 'target', '白底', 'tile'] },
  { id: 'dart-soft', zh: '靶心(浅色)', en: 'Bullseye (light)', keywords: ['direct', '直连', '靶心', '飞镖', '目标', 'target', '浅色', 'light'] },
  { id: 'arrow-right', zh: '直连(箭头)', en: 'Direct (arrow)', keywords: ['direct', '直连', '箭头', 'arrow'] },
  { id: 'arrow-right-tile', zh: '直连(箭头)(白底)', en: 'Direct (arrow) (tile)', keywords: ['direct', '直连', '箭头', 'arrow', '白底', 'tile'] },
  { id: 'arrow-right-soft', zh: '直连(箭头)(浅色)', en: 'Direct (arrow) (light)', keywords: ['direct', '直连', '箭头', 'arrow', '浅色', 'light'] },
  { id: 'arrow-up-right', zh: '直连(斜箭头)', en: 'Direct (up-right)', keywords: ['direct', '直连', '箭头', 'arrow'] },
  { id: 'arrow-up-right-tile', zh: '直连(斜箭头)(白底)', en: 'Direct (up-right) (tile)', keywords: ['direct', '直连', '箭头', 'arrow', '白底', 'tile'] },
  { id: 'arrow-up-right-soft', zh: '直连(斜箭头)(浅色)', en: 'Direct (up-right) (light)', keywords: ['direct', '直连', '箭头', 'arrow', '浅色', 'light'] },
  { id: 'green-circle', zh: '直连(绿灯)', en: 'Direct (green)', keywords: ['direct', '直连', '绿灯', '通行', 'green'] },
  { id: 'green-circle-tile', zh: '直连(绿灯)(白底)', en: 'Direct (green) (tile)', keywords: ['direct', '直连', '绿灯', '通行', 'green', '白底', 'tile'] },
  { id: 'green-circle-soft', zh: '直连(绿灯)(浅色)', en: 'Direct (green) (light)', keywords: ['direct', '直连', '绿灯', '通行', 'green', '浅色', 'light'] },
  { id: 'check', zh: '直连(对勾)', en: 'Direct (check)', keywords: ['direct', '直连', '对勾', '允许', 'check', 'allow'] },
  { id: 'check-tile', zh: '直连(对勾)(白底)', en: 'Direct (check) (tile)', keywords: ['direct', '直连', '对勾', '允许', 'check', 'allow', '白底', 'tile'] },
  { id: 'check-soft', zh: '直连(对勾)(浅色)', en: 'Direct (check) (light)', keywords: ['direct', '直连', '对勾', '允许', 'check', 'allow', '浅色', 'light'] },
  { id: 'direct', zh: '直连(公路)', en: 'Direct (road)', keywords: ['direct', '直连', '直通', '高速公路'] },
  { id: 'direct-tile', zh: '直连(公路)(白底)', en: 'Direct (road) (tile)', keywords: ['direct', '直连', '直通', '高速公路', '白底', 'tile'] },
  { id: 'direct-soft', zh: '直连(公路)(浅色)', en: 'Direct (road) (light)', keywords: ['direct', '直连', '直通', '高速公路', '浅色', 'light'] },
  // 拒绝的几种画法:叉、禁行、红灯、停止牌、禁止
  { id: 'cross', zh: '拒绝(叉)', en: 'Reject (cross)', keywords: ['reject', 'block', '拒绝', '拦截', '叉', 'cross'] },
  { id: 'cross-tile', zh: '拒绝(叉)(白底)', en: 'Reject (cross) (tile)', keywords: ['reject', 'block', '拒绝', '拦截', '叉', 'cross', '白底', 'tile'] },
  { id: 'cross-soft', zh: '拒绝(叉)(浅色)', en: 'Reject (cross) (light)', keywords: ['reject', 'block', '拒绝', '拦截', '叉', 'cross', '浅色', 'light'] },
  { id: 'cross-box', zh: '拒绝(方叉)', en: 'Reject (boxed cross)', keywords: ['reject', 'block', '拒绝', '拦截', '叉'] },
  { id: 'cross-box-tile', zh: '拒绝(方叉)(白底)', en: 'Reject (boxed cross) (tile)', keywords: ['reject', 'block', '拒绝', '拦截', '叉', '白底', 'tile'] },
  { id: 'cross-box-soft', zh: '拒绝(方叉)(浅色)', en: 'Reject (boxed cross) (light)', keywords: ['reject', 'block', '拒绝', '拦截', '叉', '浅色', 'light'] },
  { id: 'no-entry', zh: '拒绝(禁行)', en: 'Reject (no entry)', keywords: ['reject', 'block', '拒绝', '拦截', '禁行', '禁止'] },
  { id: 'no-entry-tile', zh: '拒绝(禁行)(白底)', en: 'Reject (no entry) (tile)', keywords: ['reject', 'block', '拒绝', '拦截', '禁行', '禁止', '白底', 'tile'] },
  { id: 'no-entry-soft', zh: '拒绝(禁行)(浅色)', en: 'Reject (no entry) (light)', keywords: ['reject', 'block', '拒绝', '拦截', '禁行', '禁止', '浅色', 'light'] },
  { id: 'red-circle', zh: '拒绝(红灯)', en: 'Reject (red)', keywords: ['reject', 'block', '拒绝', '拦截', '红灯', 'red'] },
  { id: 'red-circle-tile', zh: '拒绝(红灯)(白底)', en: 'Reject (red) (tile)', keywords: ['reject', 'block', '拒绝', '拦截', '红灯', 'red', '白底', 'tile'] },
  { id: 'red-circle-soft', zh: '拒绝(红灯)(浅色)', en: 'Reject (red) (light)', keywords: ['reject', 'block', '拒绝', '拦截', '红灯', 'red', '浅色', 'light'] },
  { id: 'stop-sign', zh: '拒绝(停止)', en: 'Reject (stop)', keywords: ['reject', 'block', '拒绝', '拦截', '停止', 'stop'] },
  { id: 'stop-sign-tile', zh: '拒绝(停止)(白底)', en: 'Reject (stop) (tile)', keywords: ['reject', 'block', '拒绝', '拦截', '停止', 'stop', '白底', 'tile'] },
  { id: 'stop-sign-soft', zh: '拒绝(停止)(浅色)', en: 'Reject (stop) (light)', keywords: ['reject', 'block', '拒绝', '拦截', '停止', 'stop', '浅色', 'light'] },
  { id: 'reject', zh: '拒绝(禁止)', en: 'Reject (no)', keywords: ['reject', 'block', '拒绝', '拦截', '禁止'] },
  { id: 'reject-tile', zh: '拒绝(禁止)(白底)', en: 'Reject (no) (tile)', keywords: ['reject', 'block', '拒绝', '拦截', '禁止', '白底', 'tile'] },
  { id: 'reject-soft', zh: '拒绝(禁止)(浅色)', en: 'Reject (no) (light)', keywords: ['reject', 'block', '拒绝', '拦截', '禁止', '浅色', 'light'] },
  { id: 'car', zh: '汽车', en: 'Car', keywords: ['car', '汽车', '轿车', '车'] },
  { id: 'car-tile', zh: '汽车(白底)', en: 'Car (tile)', keywords: ['car', '汽车', '轿车', '车', '白底', 'tile'] },
  { id: 'car-soft', zh: '汽车(浅色)', en: 'Car (light)', keywords: ['car', '汽车', '轿车', '车', '浅色', 'light'] },
  { id: 'taxi', zh: '出租车', en: 'Taxi', keywords: ['taxi', '出租车', '打车'] },
  { id: 'taxi-tile', zh: '出租车(白底)', en: 'Taxi (tile)', keywords: ['taxi', '出租车', '打车', '白底', 'tile'] },
  { id: 'taxi-soft', zh: '出租车(浅色)', en: 'Taxi (light)', keywords: ['taxi', '出租车', '打车', '浅色', 'light'] },
  { id: 'bus', zh: '公交车', en: 'Bus', keywords: ['bus', '公交', '巴士'] },
  { id: 'bus-tile', zh: '公交车(白底)', en: 'Bus (tile)', keywords: ['bus', '公交', '巴士', '白底', 'tile'] },
  { id: 'bus-soft', zh: '公交车(浅色)', en: 'Bus (light)', keywords: ['bus', '公交', '巴士', '浅色', 'light'] },
  { id: 'train', zh: '火车', en: 'Train', keywords: ['train', '火车', '高铁', '铁路'] },
  { id: 'train-tile', zh: '火车(白底)', en: 'Train (tile)', keywords: ['train', '火车', '高铁', '铁路', '白底', 'tile'] },
  { id: 'train-soft', zh: '火车(浅色)', en: 'Train (light)', keywords: ['train', '火车', '高铁', '铁路', '浅色', 'light'] },
  { id: 'metro', zh: '地铁', en: 'Metro', keywords: ['metro', 'subway', '地铁'] },
  { id: 'metro-tile', zh: '地铁(白底)', en: 'Metro (tile)', keywords: ['metro', 'subway', '地铁', '白底', 'tile'] },
  { id: 'metro-soft', zh: '地铁(浅色)', en: 'Metro (light)', keywords: ['metro', 'subway', '地铁', '浅色', 'light'] },
  { id: 'plane', zh: '飞机', en: 'Airplane', keywords: ['plane', '飞机', '航班', '机票'] },
  { id: 'plane-tile', zh: '飞机(白底)', en: 'Airplane (tile)', keywords: ['plane', '飞机', '航班', '机票', '白底', 'tile'] },
  { id: 'plane-soft', zh: '飞机(浅色)', en: 'Airplane (light)', keywords: ['plane', '飞机', '航班', '机票', '浅色', 'light'] },
  { id: 'ship', zh: '轮船', en: 'Ship', keywords: ['ship', '轮船', '船', '航运'] },
  { id: 'ship-tile', zh: '轮船(白底)', en: 'Ship (tile)', keywords: ['ship', '轮船', '船', '航运', '白底', 'tile'] },
  { id: 'ship-soft', zh: '轮船(浅色)', en: 'Ship (light)', keywords: ['ship', '轮船', '船', '航运', '浅色', 'light'] },
  { id: 'bike', zh: '自行车', en: 'Bicycle', keywords: ['bike', '自行车', '单车'] },
  { id: 'bike-tile', zh: '自行车(白底)', en: 'Bicycle (tile)', keywords: ['bike', '自行车', '单车', '白底', 'tile'] },
  { id: 'bike-soft', zh: '自行车(浅色)', en: 'Bicycle (light)', keywords: ['bike', '自行车', '单车', '浅色', 'light'] },
  { id: 'motorcycle', zh: '摩托车', en: 'Motorcycle', keywords: ['motorcycle', '摩托', '机车'] },
  { id: 'motorcycle-tile', zh: '摩托车(白底)', en: 'Motorcycle (tile)', keywords: ['motorcycle', '摩托', '机车', '白底', 'tile'] },
  { id: 'motorcycle-soft', zh: '摩托车(浅色)', en: 'Motorcycle (light)', keywords: ['motorcycle', '摩托', '机车', '浅色', 'light'] },
  { id: 'rocket', zh: '火箭', en: 'Rocket', keywords: ['rocket', '火箭', '加速'] },
  { id: 'rocket-tile', zh: '火箭(白底)', en: 'Rocket (tile)', keywords: ['rocket', '火箭', '加速', '白底', 'tile'] },
  { id: 'rocket-soft', zh: '火箭(浅色)', en: 'Rocket (light)', keywords: ['rocket', '火箭', '加速', '浅色', 'light'] },
  { id: 'soccer', zh: '足球', en: 'Soccer', keywords: ['soccer', 'football', '足球', '运动'] },
  { id: 'soccer-tile', zh: '足球(白底)', en: 'Soccer (tile)', keywords: ['soccer', 'football', '足球', '运动', '白底', 'tile'] },
  { id: 'soccer-soft', zh: '足球(浅色)', en: 'Soccer (light)', keywords: ['soccer', 'football', '足球', '运动', '浅色', 'light'] },
  { id: 'basketball', zh: '篮球', en: 'Basketball', keywords: ['basketball', '篮球', '运动'] },
  { id: 'basketball-tile', zh: '篮球(白底)', en: 'Basketball (tile)', keywords: ['basketball', '篮球', '运动', '白底', 'tile'] },
  { id: 'basketball-soft', zh: '篮球(浅色)', en: 'Basketball (light)', keywords: ['basketball', '篮球', '运动', '浅色', 'light'] },
  { id: 'tennis', zh: '网球', en: 'Tennis', keywords: ['tennis', '网球', '运动'] },
  { id: 'tennis-tile', zh: '网球(白底)', en: 'Tennis (tile)', keywords: ['tennis', '网球', '运动', '白底', 'tile'] },
  { id: 'tennis-soft', zh: '网球(浅色)', en: 'Tennis (light)', keywords: ['tennis', '网球', '运动', '浅色', 'light'] },
  { id: 'swim', zh: '游泳', en: 'Swimming', keywords: ['swim', '游泳', '运动'] },
  { id: 'swim-tile', zh: '游泳(白底)', en: 'Swimming (tile)', keywords: ['swim', '游泳', '运动', '白底', 'tile'] },
  { id: 'swim-soft', zh: '游泳(浅色)', en: 'Swimming (light)', keywords: ['swim', '游泳', '运动', '浅色', 'light'] },
  { id: 'run', zh: '跑步', en: 'Running', keywords: ['run', '跑步', '运动'] },
  { id: 'run-tile', zh: '跑步(白底)', en: 'Running (tile)', keywords: ['run', '跑步', '运动', '白底', 'tile'] },
  { id: 'run-soft', zh: '跑步(浅色)', en: 'Running (light)', keywords: ['run', '跑步', '运动', '浅色', 'light'] },
  { id: 'gym', zh: '健身', en: 'Weightlifting', keywords: ['gym', '健身', '举重', '运动'] },
  { id: 'gym-tile', zh: '健身(白底)', en: 'Weightlifting (tile)', keywords: ['gym', '健身', '举重', '运动', '白底', 'tile'] },
  { id: 'gym-soft', zh: '健身(浅色)', en: 'Weightlifting (light)', keywords: ['gym', '健身', '举重', '运动', '浅色', 'light'] },
  { id: 'trophy', zh: '奖杯', en: 'Trophy', keywords: ['trophy', '奖杯', '冠军', '比赛'] },
  { id: 'trophy-tile', zh: '奖杯(白底)', en: 'Trophy (tile)', keywords: ['trophy', '奖杯', '冠军', '比赛', '白底', 'tile'] },
  { id: 'trophy-soft', zh: '奖杯(浅色)', en: 'Trophy (light)', keywords: ['trophy', '奖杯', '冠军', '比赛', '浅色', 'light'] },
  { id: 'game', zh: '游戏', en: 'Game', keywords: ['game', '游戏', '手柄'] },
  { id: 'game-tile', zh: '游戏(白底)', en: 'Game (tile)', keywords: ['game', '游戏', '手柄', '白底', 'tile'] },
  { id: 'game-soft', zh: '游戏(浅色)', en: 'Game (light)', keywords: ['game', '游戏', '手柄', '浅色', 'light'] },
  { id: 'chess', zh: '棋', en: 'Chess', keywords: ['chess', '棋', '国际象棋'] },
  { id: 'chess-tile', zh: '棋(白底)', en: 'Chess (tile)', keywords: ['chess', '棋', '国际象棋', '白底', 'tile'] },
  { id: 'chess-soft', zh: '棋(浅色)', en: 'Chess (light)', keywords: ['chess', '棋', '国际象棋', '浅色', 'light'] },
  { id: 'flower', zh: '花', en: 'Flower', keywords: ['flower', '花', '樱花', '植物'] },
  { id: 'flower-tile', zh: '花(白底)', en: 'Flower (tile)', keywords: ['flower', '花', '樱花', '植物', '白底', 'tile'] },
  { id: 'flower-soft', zh: '花(浅色)', en: 'Flower (light)', keywords: ['flower', '花', '樱花', '植物', '浅色', 'light'] },
  { id: 'rose', zh: '玫瑰', en: 'Rose', keywords: ['rose', '玫瑰', '花'] },
  { id: 'rose-tile', zh: '玫瑰(白底)', en: 'Rose (tile)', keywords: ['rose', '玫瑰', '花', '白底', 'tile'] },
  { id: 'rose-soft', zh: '玫瑰(浅色)', en: 'Rose (light)', keywords: ['rose', '玫瑰', '花', '浅色', 'light'] },
  { id: 'tree', zh: '树', en: 'Tree', keywords: ['tree', '树', '森林', '植物'] },
  { id: 'tree-tile', zh: '树(白底)', en: 'Tree (tile)', keywords: ['tree', '树', '森林', '植物', '白底', 'tile'] },
  { id: 'tree-soft', zh: '树(浅色)', en: 'Tree (light)', keywords: ['tree', '树', '森林', '植物', '浅色', 'light'] },
  { id: 'leaf', zh: '叶子', en: 'Leaf', keywords: ['leaf', '叶子', '植物', '绿色'] },
  { id: 'leaf-tile', zh: '叶子(白底)', en: 'Leaf (tile)', keywords: ['leaf', '叶子', '植物', '绿色', '白底', 'tile'] },
  { id: 'leaf-soft', zh: '叶子(浅色)', en: 'Leaf (light)', keywords: ['leaf', '叶子', '植物', '绿色', '浅色', 'light'] },
  { id: 'cactus', zh: '仙人掌', en: 'Cactus', keywords: ['cactus', '仙人掌', '植物'] },
  { id: 'cactus-tile', zh: '仙人掌(白底)', en: 'Cactus (tile)', keywords: ['cactus', '仙人掌', '植物', '白底', 'tile'] },
  { id: 'cactus-soft', zh: '仙人掌(浅色)', en: 'Cactus (light)', keywords: ['cactus', '仙人掌', '植物', '浅色', 'light'] },
  { id: 'seedling', zh: '幼苗', en: 'Seedling', keywords: ['seedling', '幼苗', '发芽', '植物'] },
  { id: 'seedling-tile', zh: '幼苗(白底)', en: 'Seedling (tile)', keywords: ['seedling', '幼苗', '发芽', '植物', '白底', 'tile'] },
  { id: 'seedling-soft', zh: '幼苗(浅色)', en: 'Seedling (light)', keywords: ['seedling', '幼苗', '发芽', '植物', '浅色', 'light'] },
  { id: 'sun', zh: '太阳', en: 'Sun', keywords: ['sun', '太阳', '晴天', '天气'] },
  { id: 'sun-tile', zh: '太阳(白底)', en: 'Sun (tile)', keywords: ['sun', '太阳', '晴天', '天气', '白底', 'tile'] },
  { id: 'sun-soft', zh: '太阳(浅色)', en: 'Sun (light)', keywords: ['sun', '太阳', '晴天', '天气', '浅色', 'light'] },
  { id: 'moon', zh: '月亮', en: 'Moon', keywords: ['moon', '月亮', '夜晚'] },
  { id: 'moon-tile', zh: '月亮(白底)', en: 'Moon (tile)', keywords: ['moon', '月亮', '夜晚', '白底', 'tile'] },
  { id: 'moon-soft', zh: '月亮(浅色)', en: 'Moon (light)', keywords: ['moon', '月亮', '夜晚', '浅色', 'light'] },
  { id: 'star', zh: '星星', en: 'Star', keywords: ['star', '星星', '收藏'] },
  { id: 'star-tile', zh: '星星(白底)', en: 'Star (tile)', keywords: ['star', '星星', '收藏', '白底', 'tile'] },
  { id: 'star-soft', zh: '星星(浅色)', en: 'Star (light)', keywords: ['star', '星星', '收藏', '浅色', 'light'] },
  { id: 'rainbow', zh: '彩虹', en: 'Rainbow', keywords: ['rainbow', '彩虹'] },
  { id: 'rainbow-tile', zh: '彩虹(白底)', en: 'Rainbow (tile)', keywords: ['rainbow', '彩虹', '白底', 'tile'] },
  { id: 'rainbow-soft', zh: '彩虹(浅色)', en: 'Rainbow (light)', keywords: ['rainbow', '彩虹', '浅色', 'light'] },
  { id: 'fire', zh: '火', en: 'Fire', keywords: ['fire', '火', '热门'] },
  { id: 'fire-tile', zh: '火(白底)', en: 'Fire (tile)', keywords: ['fire', '火', '热门', '白底', 'tile'] },
  { id: 'fire-soft', zh: '火(浅色)', en: 'Fire (light)', keywords: ['fire', '火', '热门', '浅色', 'light'] },
  { id: 'water', zh: '水滴', en: 'Droplet', keywords: ['water', '水', '水滴'] },
  { id: 'water-tile', zh: '水滴(白底)', en: 'Droplet (tile)', keywords: ['water', '水', '水滴', '白底', 'tile'] },
  { id: 'water-soft', zh: '水滴(浅色)', en: 'Droplet (light)', keywords: ['water', '水', '水滴', '浅色', 'light'] },
  { id: 'snow', zh: '雪花', en: 'Snowflake', keywords: ['snow', '雪', '雪花', '冬天'] },
  { id: 'snow-tile', zh: '雪花(白底)', en: 'Snowflake (tile)', keywords: ['snow', '雪', '雪花', '冬天', '白底', 'tile'] },
  { id: 'snow-soft', zh: '雪花(浅色)', en: 'Snowflake (light)', keywords: ['snow', '雪', '雪花', '冬天', '浅色', 'light'] },
  { id: 'cloud', zh: '云', en: 'Cloud', keywords: ['cloud', '云', '云朵', '天气'] },
  { id: 'cloud-tile', zh: '云(白底)', en: 'Cloud (tile)', keywords: ['cloud', '云', '云朵', '天气', '白底', 'tile'] },
  { id: 'cloud-soft', zh: '云(浅色)', en: 'Cloud (light)', keywords: ['cloud', '云', '云朵', '天气', '浅色', 'light'] },
  { id: 'mountain', zh: '山', en: 'Mountain', keywords: ['mountain', '山', '高山'] },
  { id: 'mountain-tile', zh: '山(白底)', en: 'Mountain (tile)', keywords: ['mountain', '山', '高山', '白底', 'tile'] },
  { id: 'mountain-soft', zh: '山(浅色)', en: 'Mountain (light)', keywords: ['mountain', '山', '高山', '浅色', 'light'] },
  { id: 'home', zh: '家', en: 'Home', keywords: ['home', '家', '住宅', '房子'] },
  { id: 'home-tile', zh: '家(白底)', en: 'Home (tile)', keywords: ['home', '家', '住宅', '房子', '白底', 'tile'] },
  { id: 'home-soft', zh: '家(浅色)', en: 'Home (light)', keywords: ['home', '家', '住宅', '房子', '浅色', 'light'] },
  { id: 'office', zh: '写字楼', en: 'Office', keywords: ['office', '写字楼', '办公', '公司'] },
  { id: 'office-tile', zh: '写字楼(白底)', en: 'Office (tile)', keywords: ['office', '写字楼', '办公', '公司', '白底', 'tile'] },
  { id: 'office-soft', zh: '写字楼(浅色)', en: 'Office (light)', keywords: ['office', '写字楼', '办公', '公司', '浅色', 'light'] },
  { id: 'school', zh: '学校', en: 'School', keywords: ['school', '学校', '教育'] },
  { id: 'school-tile', zh: '学校(白底)', en: 'School (tile)', keywords: ['school', '学校', '教育', '白底', 'tile'] },
  { id: 'school-soft', zh: '学校(浅色)', en: 'School (light)', keywords: ['school', '学校', '教育', '浅色', 'light'] },
  { id: 'hospital', zh: '医院', en: 'Hospital', keywords: ['hospital', '医院', '医疗'] },
  { id: 'hospital-tile', zh: '医院(白底)', en: 'Hospital (tile)', keywords: ['hospital', '医院', '医疗', '白底', 'tile'] },
  { id: 'hospital-soft', zh: '医院(浅色)', en: 'Hospital (light)', keywords: ['hospital', '医院', '医疗', '浅色', 'light'] },
  { id: 'bank', zh: '银行', en: 'Bank', keywords: ['bank', '银行', '金融'] },
  { id: 'bank-tile', zh: '银行(白底)', en: 'Bank (tile)', keywords: ['bank', '银行', '金融', '白底', 'tile'] },
  { id: 'bank-soft', zh: '银行(浅色)', en: 'Bank (light)', keywords: ['bank', '银行', '金融', '浅色', 'light'] },
  { id: 'hotel', zh: '酒店', en: 'Hotel', keywords: ['hotel', '酒店', '旅馆'] },
  { id: 'hotel-tile', zh: '酒店(白底)', en: 'Hotel (tile)', keywords: ['hotel', '酒店', '旅馆', '白底', 'tile'] },
  { id: 'hotel-soft', zh: '酒店(浅色)', en: 'Hotel (light)', keywords: ['hotel', '酒店', '旅馆', '浅色', 'light'] },
  { id: 'factory', zh: '工厂', en: 'Factory', keywords: ['factory', '工厂', '制造'] },
  { id: 'factory-tile', zh: '工厂(白底)', en: 'Factory (tile)', keywords: ['factory', '工厂', '制造', '白底', 'tile'] },
  { id: 'factory-soft', zh: '工厂(浅色)', en: 'Factory (light)', keywords: ['factory', '工厂', '制造', '浅色', 'light'] },
  // 测速、迪士尼这类站点集常用:秒表和信号格给测速,老鼠和上面的城堡给迪士尼
  // (Disney 的标识在项目用的两个 CC0 图库里都没有,只能用意象接近的)
  { id: 'stopwatch', zh: '秒表', en: 'Stopwatch', keywords: ['stopwatch', 'speed', 'speedtest', '秒表', '计时', '测速', '延迟'] },
  { id: 'stopwatch-tile', zh: '秒表(白底)', en: 'Stopwatch (tile)', keywords: ['stopwatch', 'speed', 'speedtest', '秒表', '计时', '测速', '延迟', '白底', 'tile'] },
  { id: 'stopwatch-soft', zh: '秒表(浅色)', en: 'Stopwatch (light)', keywords: ['stopwatch', 'speed', 'speedtest', '秒表', '计时', '测速', '延迟', '浅色', 'light'] },
  { id: 'signal-bars', zh: '信号格', en: 'Signal bars', keywords: ['signal', 'speed', 'speedtest', '信号', '网速', '测速', '带宽'] },
  { id: 'signal-bars-tile', zh: '信号格(白底)', en: 'Signal bars (tile)', keywords: ['signal', 'speed', 'speedtest', '信号', '网速', '测速', '带宽', '白底', 'tile'] },
  { id: 'signal-bars-soft', zh: '信号格(浅色)', en: 'Signal bars (light)', keywords: ['signal', 'speed', 'speedtest', '信号', '网速', '测速', '带宽', '浅色', 'light'] },
  { id: 'mouse-face', zh: '老鼠', en: 'Mouse', keywords: ['mouse', 'disney', '老鼠', '米老鼠', '迪士尼', '迪斯尼'] },
  { id: 'mouse-face-tile', zh: '老鼠(白底)', en: 'Mouse (tile)', keywords: ['mouse', 'disney', '老鼠', '米老鼠', '迪士尼', '迪斯尼', '白底', 'tile'] },
  { id: 'mouse-face-soft', zh: '老鼠(浅色)', en: 'Mouse (light)', keywords: ['mouse', 'disney', '老鼠', '米老鼠', '迪士尼', '迪斯尼', '浅色', 'light'] },
  { id: 'castle', zh: '城堡', en: 'Castle', keywords: ['castle', '城堡', 'disney', '迪士尼', '迪斯尼'] },
  { id: 'castle-tile', zh: '城堡(白底)', en: 'Castle (tile)', keywords: ['castle', '城堡', 'disney', '迪士尼', '迪斯尼', '白底', 'tile'] },
  { id: 'castle-soft', zh: '城堡(浅色)', en: 'Castle (light)', keywords: ['castle', '城堡', 'disney', '迪士尼', '迪斯尼', '浅色', 'light'] },
  { id: 'store', zh: '便利店', en: 'Store', keywords: ['store', '便利店', '商店', '购物'] },
  { id: 'store-tile', zh: '便利店(白底)', en: 'Store (tile)', keywords: ['store', '便利店', '商店', '购物', '白底', 'tile'] },
  { id: 'store-soft', zh: '便利店(浅色)', en: 'Store (light)', keywords: ['store', '便利店', '商店', '购物', '浅色', 'light'] },
  { id: 'city', zh: '城市', en: 'Cityscape', keywords: ['city', '城市', '都市'] },
  { id: 'city-tile', zh: '城市(白底)', en: 'Cityscape (tile)', keywords: ['city', '城市', '都市', '白底', 'tile'] },
  { id: 'city-soft', zh: '城市(浅色)', en: 'Cityscape (light)', keywords: ['city', '城市', '都市', '浅色', 'light'] },
  { id: 'phone', zh: '手机', en: 'Phone', keywords: ['phone', '手机', '移动'] },
  { id: 'phone-tile', zh: '手机(白底)', en: 'Phone (tile)', keywords: ['phone', '手机', '移动', '白底', 'tile'] },
  { id: 'phone-soft', zh: '手机(浅色)', en: 'Phone (light)', keywords: ['phone', '手机', '移动', '浅色', 'light'] },
  { id: 'laptop', zh: '笔记本', en: 'Laptop', keywords: ['laptop', '电脑', '笔记本'] },
  { id: 'laptop-tile', zh: '笔记本(白底)', en: 'Laptop (tile)', keywords: ['laptop', '电脑', '笔记本', '白底', 'tile'] },
  { id: 'laptop-soft', zh: '笔记本(浅色)', en: 'Laptop (light)', keywords: ['laptop', '电脑', '笔记本', '浅色', 'light'] },
  { id: 'tv', zh: '电视', en: 'TV', keywords: ['tv', '电视', '影视'] },
  { id: 'tv-tile', zh: '电视(白底)', en: 'TV (tile)', keywords: ['tv', '电视', '影视', '白底', 'tile'] },
  { id: 'tv-soft', zh: '电视(浅色)', en: 'TV (light)', keywords: ['tv', '电视', '影视', '浅色', 'light'] },
  { id: 'camera', zh: '相机', en: 'Camera', keywords: ['camera', '相机', '拍照'] },
  { id: 'camera-tile', zh: '相机(白底)', en: 'Camera (tile)', keywords: ['camera', '相机', '拍照', '白底', 'tile'] },
  { id: 'camera-soft', zh: '相机(浅色)', en: 'Camera (light)', keywords: ['camera', '相机', '拍照', '浅色', 'light'] },
  { id: 'headphone', zh: '耳机', en: 'Headphone', keywords: ['headphone', '耳机', '音乐'] },
  { id: 'headphone-tile', zh: '耳机(白底)', en: 'Headphone (tile)', keywords: ['headphone', '耳机', '音乐', '白底', 'tile'] },
  { id: 'headphone-soft', zh: '耳机(浅色)', en: 'Headphone (light)', keywords: ['headphone', '耳机', '音乐', '浅色', 'light'] },
  { id: 'book', zh: '书', en: 'Books', keywords: ['book', '书', '阅读', '学习'] },
  { id: 'book-tile', zh: '书(白底)', en: 'Books (tile)', keywords: ['book', '书', '阅读', '学习', '白底', 'tile'] },
  { id: 'book-soft', zh: '书(浅色)', en: 'Books (light)', keywords: ['book', '书', '阅读', '学习', '浅色', 'light'] },
  { id: 'mail', zh: '邮件', en: 'Mail', keywords: ['mail', '邮件', '信'] },
  { id: 'mail-tile', zh: '邮件(白底)', en: 'Mail (tile)', keywords: ['mail', '邮件', '信', '白底', 'tile'] },
  { id: 'mail-soft', zh: '邮件(浅色)', en: 'Mail (light)', keywords: ['mail', '邮件', '信', '浅色', 'light'] },
  { id: 'lock', zh: '锁', en: 'Lock', keywords: ['lock', '锁', '安全', '加密'] },
  { id: 'lock-tile', zh: '锁(白底)', en: 'Lock (tile)', keywords: ['lock', '锁', '安全', '加密', '白底', 'tile'] },
  { id: 'lock-soft', zh: '锁(浅色)', en: 'Lock (light)', keywords: ['lock', '锁', '安全', '加密', '浅色', 'light'] },
  { id: 'key', zh: '钥匙', en: 'Key', keywords: ['key', '钥匙', '密钥'] },
  { id: 'key-tile', zh: '钥匙(白底)', en: 'Key (tile)', keywords: ['key', '钥匙', '密钥', '白底', 'tile'] },
  { id: 'key-soft', zh: '钥匙(浅色)', en: 'Key (light)', keywords: ['key', '钥匙', '密钥', '浅色', 'light'] },
  { id: 'gear', zh: '齿轮', en: 'Gear', keywords: ['gear', '齿轮', '设置', '配置'] },
  { id: 'gear-tile', zh: '齿轮(白底)', en: 'Gear (tile)', keywords: ['gear', '齿轮', '设置', '配置', '白底', 'tile'] },
  { id: 'gear-soft', zh: '齿轮(浅色)', en: 'Gear (light)', keywords: ['gear', '齿轮', '设置', '配置', '浅色', 'light'] },
  { id: 'tool', zh: '扳手', en: 'Wrench', keywords: ['tool', '工具', '扳手', '维修'] },
  { id: 'tool-tile', zh: '扳手(白底)', en: 'Wrench (tile)', keywords: ['tool', '工具', '扳手', '维修', '白底', 'tile'] },
  { id: 'tool-soft', zh: '扳手(浅色)', en: 'Wrench (light)', keywords: ['tool', '工具', '扳手', '维修', '浅色', 'light'] },
  { id: 'chart', zh: '图表', en: 'Chart', keywords: ['chart', '图表', '统计', '数据'] },
  { id: 'chart-tile', zh: '图表(白底)', en: 'Chart (tile)', keywords: ['chart', '图表', '统计', '数据', '白底', 'tile'] },
  { id: 'chart-soft', zh: '图表(浅色)', en: 'Chart (light)', keywords: ['chart', '图表', '统计', '数据', '浅色', 'light'] },
  { id: 'clock', zh: '闹钟', en: 'Clock', keywords: ['clock', '时钟', '闹钟', '时间'] },
  { id: 'clock-tile', zh: '闹钟(白底)', en: 'Clock (tile)', keywords: ['clock', '时钟', '闹钟', '时间', '白底', 'tile'] },
  { id: 'clock-soft', zh: '闹钟(浅色)', en: 'Clock (light)', keywords: ['clock', '时钟', '闹钟', '时间', '浅色', 'light'] },
  { id: 'calendar', zh: '日历', en: 'Calendar', keywords: ['calendar', '日历', '日期'] },
  { id: 'calendar-tile', zh: '日历(白底)', en: 'Calendar (tile)', keywords: ['calendar', '日历', '日期', '白底', 'tile'] },
  { id: 'calendar-soft', zh: '日历(浅色)', en: 'Calendar (light)', keywords: ['calendar', '日历', '日期', '浅色', 'light'] },
  { id: 'folder', zh: '文件夹', en: 'Folder', keywords: ['folder', '文件夹', '目录'] },
  { id: 'folder-tile', zh: '文件夹(白底)', en: 'Folder (tile)', keywords: ['folder', '文件夹', '目录', '白底', 'tile'] },
  { id: 'folder-soft', zh: '文件夹(浅色)', en: 'Folder (light)', keywords: ['folder', '文件夹', '目录', '浅色', 'light'] },
  { id: 'pin', zh: '图钉', en: 'Pin', keywords: ['pin', '图钉', '置顶', '标记'] },
  { id: 'pin-tile', zh: '图钉(白底)', en: 'Pin (tile)', keywords: ['pin', '图钉', '置顶', '标记', '白底', 'tile'] },
  { id: 'pin-soft', zh: '图钉(浅色)', en: 'Pin (light)', keywords: ['pin', '图钉', '置顶', '标记', '浅色', 'light'] },
  { id: 'bulb', zh: '灯泡', en: 'Bulb', keywords: ['bulb', '灯泡', '想法', '创意'] },
  { id: 'bulb-tile', zh: '灯泡(白底)', en: 'Bulb (tile)', keywords: ['bulb', '灯泡', '想法', '创意', '白底', 'tile'] },
  { id: 'bulb-soft', zh: '灯泡(浅色)', en: 'Bulb (light)', keywords: ['bulb', '灯泡', '想法', '创意', '浅色', 'light'] },
  { id: 'battery', zh: '电池', en: 'Battery', keywords: ['battery', '电池', '电量'] },
  { id: 'battery-tile', zh: '电池(白底)', en: 'Battery (tile)', keywords: ['battery', '电池', '电量', '白底', 'tile'] },
  { id: 'battery-soft', zh: '电池(浅色)', en: 'Battery (light)', keywords: ['battery', '电池', '电量', '浅色', 'light'] },
  { id: 'satellite', zh: '卫星天线', en: 'Satellite', keywords: ['satellite', '卫星', '天线', '信号'] },
  { id: 'satellite-tile', zh: '卫星天线(白底)', en: 'Satellite (tile)', keywords: ['satellite', '卫星', '天线', '信号', '白底', 'tile'] },
  { id: 'satellite-soft', zh: '卫星天线(浅色)', en: 'Satellite (light)', keywords: ['satellite', '卫星', '天线', '信号', '浅色', 'light'] },
  { id: 'shield', zh: '盾牌', en: 'Shield', keywords: ['shield', '盾牌', '防护', '安全'] },
  { id: 'shield-tile', zh: '盾牌(白底)', en: 'Shield (tile)', keywords: ['shield', '盾牌', '防护', '安全', '白底', 'tile'] },
  { id: 'shield-soft', zh: '盾牌(浅色)', en: 'Shield (light)', keywords: ['shield', '盾牌', '防护', '安全', '浅色', 'light'] },
  { id: 'globe-net', zh: '网络', en: 'Globe with meridians', keywords: ['globe', '网络', '互联网', 'www'] },
  { id: 'globe-net-tile', zh: '网络(白底)', en: 'Globe with meridians (tile)', keywords: ['globe', '网络', '互联网', 'www', '白底', 'tile'] },
  { id: 'globe-net-soft', zh: '网络(浅色)', en: 'Globe with meridians (light)', keywords: ['globe', '网络', '互联网', 'www', '浅色', 'light'] },
  { id: 'link', zh: '链接', en: 'Link', keywords: ['link', '链接', '连接'] },
  { id: 'link-tile', zh: '链接(白底)', en: 'Link (tile)', keywords: ['link', '链接', '连接', '白底', 'tile'] },
  { id: 'link-soft', zh: '链接(浅色)', en: 'Link (light)', keywords: ['link', '链接', '连接', '浅色', 'light'] },
  { id: 'coffee', zh: '咖啡', en: 'Coffee', keywords: ['coffee', '咖啡'] },
  { id: 'coffee-tile', zh: '咖啡(白底)', en: 'Coffee (tile)', keywords: ['coffee', '咖啡', '白底', 'tile'] },
  { id: 'coffee-soft', zh: '咖啡(浅色)', en: 'Coffee (light)', keywords: ['coffee', '咖啡', '浅色', 'light'] },
  { id: 'tea', zh: '茶', en: 'Tea', keywords: ['tea', '茶', '茶饮'] },
  { id: 'tea-tile', zh: '茶(白底)', en: 'Tea (tile)', keywords: ['tea', '茶', '茶饮', '白底', 'tile'] },
  { id: 'tea-soft', zh: '茶(浅色)', en: 'Tea (light)', keywords: ['tea', '茶', '茶饮', '浅色', 'light'] },
  { id: 'burger', zh: '汉堡', en: 'Burger', keywords: ['burger', '汉堡', '快餐', '美食'] },
  { id: 'burger-tile', zh: '汉堡(白底)', en: 'Burger (tile)', keywords: ['burger', '汉堡', '快餐', '美食', '白底', 'tile'] },
  { id: 'burger-soft', zh: '汉堡(浅色)', en: 'Burger (light)', keywords: ['burger', '汉堡', '快餐', '美食', '浅色', 'light'] },
  { id: 'pizza', zh: '披萨', en: 'Pizza', keywords: ['pizza', '披萨', '美食'] },
  { id: 'pizza-tile', zh: '披萨(白底)', en: 'Pizza (tile)', keywords: ['pizza', '披萨', '美食', '白底', 'tile'] },
  { id: 'pizza-soft', zh: '披萨(浅色)', en: 'Pizza (light)', keywords: ['pizza', '披萨', '美食', '浅色', 'light'] },
  { id: 'cake', zh: '蛋糕', en: 'Cake', keywords: ['cake', '蛋糕', '生日'] },
  { id: 'cake-tile', zh: '蛋糕(白底)', en: 'Cake (tile)', keywords: ['cake', '蛋糕', '生日', '白底', 'tile'] },
  { id: 'cake-soft', zh: '蛋糕(浅色)', en: 'Cake (light)', keywords: ['cake', '蛋糕', '生日', '浅色', 'light'] },
  { id: 'beer', zh: '啤酒', en: 'Beer', keywords: ['beer', '啤酒', '酒'] },
  { id: 'beer-tile', zh: '啤酒(白底)', en: 'Beer (tile)', keywords: ['beer', '啤酒', '酒', '白底', 'tile'] },
  { id: 'beer-soft', zh: '啤酒(浅色)', en: 'Beer (light)', keywords: ['beer', '啤酒', '酒', '浅色', 'light'] },
  { id: 'cat', zh: '猫', en: 'Cat', keywords: ['cat', '猫', '宠物'] },
  { id: 'cat-tile', zh: '猫(白底)', en: 'Cat (tile)', keywords: ['cat', '猫', '宠物', '白底', 'tile'] },
  { id: 'cat-soft', zh: '猫(浅色)', en: 'Cat (light)', keywords: ['cat', '猫', '宠物', '浅色', 'light'] },
  { id: 'dog', zh: '狗', en: 'Dog', keywords: ['dog', '狗', '宠物'] },
  { id: 'dog-tile', zh: '狗(白底)', en: 'Dog (tile)', keywords: ['dog', '狗', '宠物', '白底', 'tile'] },
  { id: 'dog-soft', zh: '狗(浅色)', en: 'Dog (light)', keywords: ['dog', '狗', '宠物', '浅色', 'light'] },
  { id: 'panda', zh: '熊猫', en: 'Panda', keywords: ['panda', '熊猫'] },
  { id: 'panda-tile', zh: '熊猫(白底)', en: 'Panda (tile)', keywords: ['panda', '熊猫', '白底', 'tile'] },
  { id: 'panda-soft', zh: '熊猫(浅色)', en: 'Panda (light)', keywords: ['panda', '熊猫', '浅色', 'light'] },
  { id: 'fish', zh: '鱼', en: 'Fish', keywords: ['fish', '鱼'] },
  { id: 'fish-tile', zh: '鱼(白底)', en: 'Fish (tile)', keywords: ['fish', '鱼', '白底', 'tile'] },
  { id: 'fish-soft', zh: '鱼(浅色)', en: 'Fish (light)', keywords: ['fish', '鱼', '浅色', 'light'] },
  { id: 'bird', zh: '鸟', en: 'Bird', keywords: ['bird', '鸟'] },
  { id: 'bird-tile', zh: '鸟(白底)', en: 'Bird (tile)', keywords: ['bird', '鸟', '白底', 'tile'] },
  { id: 'bird-soft', zh: '鸟(浅色)', en: 'Bird (light)', keywords: ['bird', '鸟', '浅色', 'light'] },
  { id: 'man', zh: '男', en: 'Man', keywords: ['man', '男', '男性', '性别', 'gender', 'sex'] },
  { id: 'man-tile', zh: '男(白底)', en: 'Man (tile)', keywords: ['man', '男', '男性', '性别', 'gender', 'sex', '白底', 'tile'] },
  { id: 'man-soft', zh: '男(浅色)', en: 'Man (light)', keywords: ['man', '男', '男性', '性别', 'gender', 'sex', '浅色', 'light'] },
  { id: 'woman', zh: '女', en: 'Woman', keywords: ['woman', '女', '女性', '性别', 'gender', 'sex'] },
  { id: 'woman-tile', zh: '女(白底)', en: 'Woman (tile)', keywords: ['woman', '女', '女性', '性别', 'gender', 'sex', '白底', 'tile'] },
  { id: 'woman-soft', zh: '女(浅色)', en: 'Woman (light)', keywords: ['woman', '女', '女性', '性别', 'gender', 'sex', '浅色', 'light'] },
  { id: 'boy', zh: '男孩', en: 'Boy', keywords: ['boy', '男孩', '儿童', '孩子'] },
  { id: 'boy-tile', zh: '男孩(白底)', en: 'Boy (tile)', keywords: ['boy', '男孩', '儿童', '孩子', '白底', 'tile'] },
  { id: 'boy-soft', zh: '男孩(浅色)', en: 'Boy (light)', keywords: ['boy', '男孩', '儿童', '孩子', '浅色', 'light'] },
  { id: 'girl', zh: '女孩', en: 'Girl', keywords: ['girl', '女孩', '儿童', '孩子'] },
  { id: 'girl-tile', zh: '女孩(白底)', en: 'Girl (tile)', keywords: ['girl', '女孩', '儿童', '孩子', '白底', 'tile'] },
  { id: 'girl-soft', zh: '女孩(浅色)', en: 'Girl (light)', keywords: ['girl', '女孩', '儿童', '孩子', '浅色', 'light'] },
  { id: 'baby', zh: '婴儿', en: 'Baby', keywords: ['baby', '婴儿', '宝宝'] },
  { id: 'baby-tile', zh: '婴儿(白底)', en: 'Baby (tile)', keywords: ['baby', '婴儿', '宝宝', '白底', 'tile'] },
  { id: 'baby-soft', zh: '婴儿(浅色)', en: 'Baby (light)', keywords: ['baby', '婴儿', '宝宝', '浅色', 'light'] },
  { id: 'old-man', zh: '老人(男)', en: 'Old man', keywords: ['old', '老人', '爷爷', '长辈'] },
  { id: 'old-man-tile', zh: '老人(男)(白底)', en: 'Old man (tile)', keywords: ['old', '老人', '爷爷', '长辈', '白底', 'tile'] },
  { id: 'old-man-soft', zh: '老人(男)(浅色)', en: 'Old man (light)', keywords: ['old', '老人', '爷爷', '长辈', '浅色', 'light'] },
  { id: 'old-woman', zh: '老人(女)', en: 'Old woman', keywords: ['old', '老人', '奶奶', '长辈'] },
  { id: 'old-woman-tile', zh: '老人(女)(白底)', en: 'Old woman (tile)', keywords: ['old', '老人', '奶奶', '长辈', '白底', 'tile'] },
  { id: 'old-woman-soft', zh: '老人(女)(浅色)', en: 'Old woman (light)', keywords: ['old', '老人', '奶奶', '长辈', '浅色', 'light'] },
  { id: 'family', zh: '家庭', en: 'Family', keywords: ['family', '家庭', '一家'] },
  { id: 'family-tile', zh: '家庭(白底)', en: 'Family (tile)', keywords: ['family', '家庭', '一家', '白底', 'tile'] },
  { id: 'family-soft', zh: '家庭(浅色)', en: 'Family (light)', keywords: ['family', '家庭', '一家', '浅色', 'light'] },
  { id: 'male-sign', zh: '男性符号', en: 'Male sign', keywords: ['male', '男', '性别', '符号', 'gender', 'sex'] },
  { id: 'male-sign-tile', zh: '男性符号(白底)', en: 'Male sign (tile)', keywords: ['male', '男', '性别', '符号', 'gender', 'sex', '白底', 'tile'] },
  { id: 'male-sign-soft', zh: '男性符号(浅色)', en: 'Male sign (light)', keywords: ['male', '男', '性别', '符号', 'gender', 'sex', '浅色', 'light'] },
  { id: 'female-sign', zh: '女性符号', en: 'Female sign', keywords: ['female', '女', '性别', '符号', 'gender', 'sex'] },
  { id: 'female-sign-tile', zh: '女性符号(白底)', en: 'Female sign (tile)', keywords: ['female', '女', '性别', '符号', 'gender', 'sex', '白底', 'tile'] },
  { id: 'female-sign-soft', zh: '女性符号(浅色)', en: 'Female sign (light)', keywords: ['female', '女', '性别', '符号', 'gender', 'sex', '浅色', 'light'] },
  { id: 'heart', zh: '爱心', en: 'Heart', keywords: ['heart', '爱心', '喜欢', '收藏'] },
  { id: 'heart-tile', zh: '爱心(白底)', en: 'Heart (tile)', keywords: ['heart', '爱心', '喜欢', '收藏', '白底', 'tile'] },
  { id: 'heart-soft', zh: '爱心(浅色)', en: 'Heart (light)', keywords: ['heart', '爱心', '喜欢', '收藏', '浅色', 'light'] },
  { id: 'music', zh: '音乐', en: 'Music', keywords: ['music', '音乐', '歌曲'] },
  { id: 'music-tile', zh: '音乐(白底)', en: 'Music (tile)', keywords: ['music', '音乐', '歌曲', '白底', 'tile'] },
  { id: 'music-soft', zh: '音乐(浅色)', en: 'Music (light)', keywords: ['music', '音乐', '歌曲', '浅色', 'light'] },
  { id: 'film', zh: '电影', en: 'Film', keywords: ['film', '电影', '影视', '视频'] },
  { id: 'film-tile', zh: '电影(白底)', en: 'Film (tile)', keywords: ['film', '电影', '影视', '视频', '白底', 'tile'] },
  { id: 'film-soft', zh: '电影(浅色)', en: 'Film (light)', keywords: ['film', '电影', '影视', '视频', '浅色', 'light'] },
  { id: 'gift', zh: '礼物', en: 'Gift', keywords: ['gift', '礼物', '赠送'] },
  { id: 'gift-tile', zh: '礼物(白底)', en: 'Gift (tile)', keywords: ['gift', '礼物', '赠送', '白底', 'tile'] },
  { id: 'gift-soft', zh: '礼物(浅色)', en: 'Gift (light)', keywords: ['gift', '礼物', '赠送', '浅色', 'light'] },
  { id: 'money', zh: '钱袋', en: 'Money', keywords: ['money', '钱', '金钱', '财务'] },
  { id: 'money-tile', zh: '钱袋(白底)', en: 'Money (tile)', keywords: ['money', '钱', '金钱', '财务', '白底', 'tile'] },
  { id: 'money-soft', zh: '钱袋(浅色)', en: 'Money (light)', keywords: ['money', '钱', '金钱', '财务', '浅色', 'light'] },
  // 货币与收银:纸币(美元/日元/欧元/英镑)、硬币、汇率、转账、银行卡、取款机、收据、购物袋、行情、宝石
  { id: 'dollar', zh: '美元', en: 'Dollar', keywords: ['dollar', 'usd', '美元', '纸币', '钞票', '货币', 'currency', 'money'] },
  { id: 'dollar-tile', zh: '美元(白底)', en: 'Dollar (tile)', keywords: ['dollar', 'usd', '美元', '纸币', '钞票', '货币', 'currency', 'money', '白底', 'tile'] },
  { id: 'dollar-soft', zh: '美元(浅色)', en: 'Dollar (light)', keywords: ['dollar', 'usd', '美元', '纸币', '钞票', '货币', 'currency', 'money', '浅色', 'light'] },
  { id: 'yen', zh: '日元', en: 'Yen', keywords: ['yen', 'jpy', '日元', '纸币', '货币', 'currency', 'money'] },
  { id: 'yen-tile', zh: '日元(白底)', en: 'Yen (tile)', keywords: ['yen', 'jpy', '日元', '纸币', '货币', 'currency', 'money', '白底', 'tile'] },
  { id: 'yen-soft', zh: '日元(浅色)', en: 'Yen (light)', keywords: ['yen', 'jpy', '日元', '纸币', '货币', 'currency', 'money', '浅色', 'light'] },
  { id: 'euro', zh: '欧元', en: 'Euro', keywords: ['euro', 'eur', '欧元', '纸币', '货币', 'currency', 'money'] },
  { id: 'euro-tile', zh: '欧元(白底)', en: 'Euro (tile)', keywords: ['euro', 'eur', '欧元', '纸币', '货币', 'currency', 'money', '白底', 'tile'] },
  { id: 'euro-soft', zh: '欧元(浅色)', en: 'Euro (light)', keywords: ['euro', 'eur', '欧元', '纸币', '货币', 'currency', 'money', '浅色', 'light'] },
  { id: 'pound', zh: '英镑', en: 'Pound', keywords: ['pound', 'gbp', '英镑', '纸币', '货币', 'currency', 'money'] },
  { id: 'pound-tile', zh: '英镑(白底)', en: 'Pound (tile)', keywords: ['pound', 'gbp', '英镑', '纸币', '货币', 'currency', 'money', '白底', 'tile'] },
  { id: 'pound-soft', zh: '英镑(浅色)', en: 'Pound (light)', keywords: ['pound', 'gbp', '英镑', '纸币', '货币', 'currency', 'money', '浅色', 'light'] },
  { id: 'coin', zh: '硬币', en: 'Coin', keywords: ['coin', '硬币', '金币', '货币', 'currency', 'crypto', '币'] },
  { id: 'coin-tile', zh: '硬币(白底)', en: 'Coin (tile)', keywords: ['coin', '硬币', '金币', '货币', 'currency', 'crypto', '币', '白底', 'tile'] },
  { id: 'coin-soft', zh: '硬币(浅色)', en: 'Coin (light)', keywords: ['coin', '硬币', '金币', '货币', 'currency', 'crypto', '币', '浅色', 'light'] },
  { id: 'dollar-sign', zh: '美元符号', en: 'Dollar sign', keywords: ['dollar', 'usd', '美元', '$', '货币', 'currency', 'money'] },
  { id: 'dollar-sign-tile', zh: '美元符号(白底)', en: 'Dollar sign (tile)', keywords: ['dollar', 'usd', '美元', '$', '货币', 'currency', 'money', '白底', 'tile'] },
  { id: 'dollar-sign-soft', zh: '美元符号(浅色)', en: 'Dollar sign (light)', keywords: ['dollar', 'usd', '美元', '$', '货币', 'currency', 'money', '浅色', 'light'] },
  { id: 'exchange', zh: '汇率', en: 'Currency exchange', keywords: ['exchange', 'forex', '汇率', '换汇', '外汇', '货币', 'currency'] },
  { id: 'exchange-tile', zh: '汇率(白底)', en: 'Currency exchange (tile)', keywords: ['exchange', 'forex', '汇率', '换汇', '外汇', '货币', 'currency', '白底', 'tile'] },
  { id: 'exchange-soft', zh: '汇率(浅色)', en: 'Currency exchange (light)', keywords: ['exchange', 'forex', '汇率', '换汇', '外汇', '货币', 'currency', '浅色', 'light'] },
  { id: 'money-wings', zh: '转账', en: 'Money transfer', keywords: ['money', 'transfer', '转账', '汇款', '支付', 'pay'] },
  { id: 'money-wings-tile', zh: '转账(白底)', en: 'Money transfer (tile)', keywords: ['money', 'transfer', '转账', '汇款', '支付', 'pay', '白底', 'tile'] },
  { id: 'money-wings-soft', zh: '转账(浅色)', en: 'Money transfer (light)', keywords: ['money', 'transfer', '转账', '汇款', '支付', 'pay', '浅色', 'light'] },
  { id: 'credit-card', zh: '银行卡', en: 'Credit card', keywords: ['credit card', 'card', '银行卡', '信用卡', '支付', 'pay', '收银'] },
  { id: 'credit-card-tile', zh: '银行卡(白底)', en: 'Credit card (tile)', keywords: ['credit card', 'card', '银行卡', '信用卡', '支付', 'pay', '收银', '白底', 'tile'] },
  { id: 'credit-card-soft', zh: '银行卡(浅色)', en: 'Credit card (light)', keywords: ['credit card', 'card', '银行卡', '信用卡', '支付', 'pay', '收银', '浅色', 'light'] },
  { id: 'atm', zh: '取款机', en: 'ATM', keywords: ['atm', '取款机', '银行', 'bank', '现金', 'cash'] },
  { id: 'atm-tile', zh: '取款机(白底)', en: 'ATM (tile)', keywords: ['atm', '取款机', '银行', 'bank', '现金', 'cash', '白底', 'tile'] },
  { id: 'atm-soft', zh: '取款机(浅色)', en: 'ATM (light)', keywords: ['atm', '取款机', '银行', 'bank', '现金', 'cash', '浅色', 'light'] },
  { id: 'receipt', zh: '收据', en: 'Receipt', keywords: ['receipt', '收据', '账单', '发票', '收银', '支付', 'pay'] },
  { id: 'receipt-tile', zh: '收据(白底)', en: 'Receipt (tile)', keywords: ['receipt', '收据', '账单', '发票', '收银', '支付', 'pay', '白底', 'tile'] },
  { id: 'receipt-soft', zh: '收据(浅色)', en: 'Receipt (light)', keywords: ['receipt', '收据', '账单', '发票', '收银', '支付', 'pay', '浅色', 'light'] },
  { id: 'shopping-bags', zh: '购物袋', en: 'Shopping bags', keywords: ['shopping', '购物', '购物袋', '电商', '消费'] },
  { id: 'shopping-bags-tile', zh: '购物袋(白底)', en: 'Shopping bags (tile)', keywords: ['shopping', '购物', '购物袋', '电商', '消费', '白底', 'tile'] },
  { id: 'shopping-bags-soft', zh: '购物袋(浅色)', en: 'Shopping bags (light)', keywords: ['shopping', '购物', '购物袋', '电商', '消费', '浅色', 'light'] },
  { id: 'chart-yen', zh: '行情', en: 'Market chart', keywords: ['chart', 'stock', '行情', '股票', '涨', '金融', 'crypto'] },
  { id: 'chart-yen-tile', zh: '行情(白底)', en: 'Market chart (tile)', keywords: ['chart', 'stock', '行情', '股票', '涨', '金融', 'crypto', '白底', 'tile'] },
  { id: 'chart-yen-soft', zh: '行情(浅色)', en: 'Market chart (light)', keywords: ['chart', 'stock', '行情', '股票', '涨', '金融', 'crypto', '浅色', 'light'] },
  { id: 'gem', zh: '宝石', en: 'Gem', keywords: ['gem', 'diamond', '宝石', '钻石', 'crypto'] },
  { id: 'gem-tile', zh: '宝石(白底)', en: 'Gem (tile)', keywords: ['gem', 'diamond', '宝石', '钻石', 'crypto', '白底', 'tile'] },
  { id: 'gem-soft', zh: '宝石(浅色)', en: 'Gem (light)', keywords: ['gem', 'diamond', '宝石', '钻石', 'crypto', '浅色', 'light'] },
  { id: 'cart', zh: '购物车', en: 'Cart', keywords: ['cart', '购物车', '购物', '电商'] },
  { id: 'cart-tile', zh: '购物车(白底)', en: 'Cart (tile)', keywords: ['cart', '购物车', '购物', '电商', '白底', 'tile'] },
  { id: 'cart-soft', zh: '购物车(浅色)', en: 'Cart (light)', keywords: ['cart', '购物车', '购物', '电商', '浅色', 'light'] },
  { id: 'briefcase', zh: '公文包', en: 'Briefcase', keywords: ['briefcase', '公文包', '工作', '商务'] },
  { id: 'briefcase-tile', zh: '公文包(白底)', en: 'Briefcase (tile)', keywords: ['briefcase', '公文包', '工作', '商务', '白底', 'tile'] },
  { id: 'briefcase-soft', zh: '公文包(浅色)', en: 'Briefcase (light)', keywords: ['briefcase', '公文包', '工作', '商务', '浅色', 'light'] },
  { id: 'medal', zh: '金牌', en: 'Medal', keywords: ['medal', '金牌', '第一', '奖'] },
  { id: 'medal-tile', zh: '金牌(白底)', en: 'Medal (tile)', keywords: ['medal', '金牌', '第一', '奖', '白底', 'tile'] },
  { id: 'medal-soft', zh: '金牌(浅色)', en: 'Medal (light)', keywords: ['medal', '金牌', '第一', '奖', '浅色', 'light'] },
  { id: 'checkered-flag', zh: '终点旗', en: 'Checkered flag', keywords: ['flag', '终点', '比赛', '完成'] },
  { id: 'checkered-flag-tile', zh: '终点旗(白底)', en: 'Checkered flag (tile)', keywords: ['flag', '终点', '比赛', '完成', '白底', 'tile'] },
  { id: 'checkered-flag-soft', zh: '终点旗(浅色)', en: 'Checkered flag (light)', keywords: ['flag', '终点', '比赛', '完成', '浅色', 'light'] },
  { id: 'warning', zh: '警告', en: 'Warning', keywords: ['warning', '警告', '注意', '提醒'] },
  { id: 'warning-tile', zh: '警告(白底)', en: 'Warning (tile)', keywords: ['warning', '警告', '注意', '提醒', '白底', 'tile'] },
  { id: 'warning-soft', zh: '警告(浅色)', en: 'Warning (light)', keywords: ['warning', '警告', '注意', '提醒', '浅色', 'light'] },
  { id: 'question', zh: '问号', en: 'Question', keywords: ['question', '问号', '疑问', '未知'] },
  { id: 'question-tile', zh: '问号(白底)', en: 'Question (tile)', keywords: ['question', '问号', '疑问', '未知', '白底', 'tile'] },
  { id: 'question-soft', zh: '问号(浅色)', en: 'Question (light)', keywords: ['question', '问号', '疑问', '未知', '浅色', 'light'] },
  { id: 'bell', zh: '铃铛', en: 'Bell', keywords: ['bell', '铃铛', '通知', '提醒'] },
  { id: 'bell-tile', zh: '铃铛(白底)', en: 'Bell (tile)', keywords: ['bell', '铃铛', '通知', '提醒', '白底', 'tile'] },
  { id: 'bell-soft', zh: '铃铛(浅色)', en: 'Bell (light)', keywords: ['bell', '铃铛', '通知', '提醒', '浅色', 'light'] },
  { id: 'label', zh: '标签', en: 'Label', keywords: ['label', '标签', 'tag', '分类'] },
  { id: 'label-tile', zh: '标签(白底)', en: 'Label (tile)', keywords: ['label', '标签', 'tag', '分类', '白底', 'tile'] },
  { id: 'label-soft', zh: '标签(浅色)', en: 'Label (light)', keywords: ['label', '标签', 'tag', '分类', '浅色', 'light'] },
  { id: 'package', zh: '包裹', en: 'Package', keywords: ['package', '包裹', '快递', '打包'] },
  { id: 'package-tile', zh: '包裹(白底)', en: 'Package (tile)', keywords: ['package', '包裹', '快递', '打包', '白底', 'tile'] },
  { id: 'package-soft', zh: '包裹(浅色)', en: 'Package (light)', keywords: ['package', '包裹', '快递', '打包', '浅色', 'light'] },
  { id: 'wrench-hammer', zh: '工具箱', en: 'Tools', keywords: ['tools', '工具', '维修'] },
  { id: 'wrench-hammer-tile', zh: '工具箱(白底)', en: 'Tools (tile)', keywords: ['tools', '工具', '维修', '白底', 'tile'] },
  { id: 'wrench-hammer-soft', zh: '工具箱(浅色)', en: 'Tools (light)', keywords: ['tools', '工具', '维修', '浅色', 'light'] },
  { id: 'magnifier', zh: '放大镜', en: 'Magnifier', keywords: ['search', '搜索', '放大镜', '查找'] },
  { id: 'magnifier-tile', zh: '放大镜(白底)', en: 'Magnifier (tile)', keywords: ['search', '搜索', '放大镜', '查找', '白底', 'tile'] },
  { id: 'magnifier-soft', zh: '放大镜(浅色)', en: 'Magnifier (light)', keywords: ['search', '搜索', '放大镜', '查找', '浅色', 'light'] },
  // 中国地图剪影:轮廓来自 johan/world.geo.json(Natural Earth 数据,公有领域),含台湾、海南
  { id: 'china-map', zh: '中国地图', en: 'China map', keywords: ['china', 'cn', '中国', '地图', 'map', '国内'] },
  { id: 'china-map-tile', zh: '中国地图(白底)', en: 'China map (tile)', keywords: ['china', 'cn', '中国', '地图', 'map', '国内', '白底', 'tile'] },
  { id: 'china-map-soft', zh: '中国地图(浅色)', en: 'China map (light)', keywords: ['china', 'cn', '中国', '地图', 'map', '国内', '浅色', 'light'] },
  // 长城(手绘剪影)与 防火墙(Twemoji 砖墙 + 火)
  { id: 'great-wall', zh: '长城', en: 'Great Wall', keywords: ['great wall', 'gfw', '长城', '墙', '中国'] },
  { id: 'great-wall-tile', zh: '长城(白底)', en: 'Great Wall (tile)', keywords: ['great wall', 'gfw', '长城', '墙', '白底', 'tile'] },
  { id: 'great-wall-soft', zh: '长城(浅色)', en: 'Great Wall (light)', keywords: ['great wall', 'gfw', '长城', '墙', '浅色', 'light'] },
  { id: 'firewall', zh: '防火墙', en: 'Firewall', keywords: ['firewall', 'gfw', '防火墙', '拦截', '墙', '火'] },
  { id: 'firewall-tile', zh: '防火墙(白底)', en: 'Firewall (tile)', keywords: ['firewall', 'gfw', '防火墙', '拦截', '白底', 'tile'] },
  { id: 'firewall-soft', zh: '防火墙(浅色)', en: 'Firewall (light)', keywords: ['firewall', 'gfw', '防火墙', '拦截', '浅色', 'light'] },
]

// 图标值统一带前缀存,和国旗(HK)、地球(globe:asia)、公司(brand:google)区分开
export const MISC_PREFIX = 'misc:'

export const isMiscIcon = (value?: string): boolean => /^misc:/i.test(String(value || ''))

export const findMiscIcon = (value?: string): MiscIcon | undefined => {
  if (!isMiscIcon(value)) return undefined
  const id = String(value).slice(MISC_PREFIX.length).toLowerCase()
  return MISC_ICONS.find((i) => i.id === id)
}

export const miscIconName = (i: MiscIcon, locale: string): string => (locale.startsWith('zh') ? i.zh : i.en)
